Color Tokens
DaleStudy/dale-ui pull request #28
Opened 2024-12-31 02:14 UTC by DaleSeo

디자인 시스템의 근간이 되는 색상 관련 토큰을 정의하고 PandaCSS에 설정하였습니다. 스토리북에서 쉬운 다크 모드 전환을 위해서 관련 애드온도 설치하였습니다.

2024-12-31 02:25 UTC, DaleSeo commented on .storybook/preview.ts
> +  ],
이 설정을 통해 툴바에 라이트/다크 모드 전환 버튼이 생깁니다.

![Shot 2024-12-30 at 21 17 09](https://github.com/user-attachments/assets/1b9b6ed0-b154-4620-89f5-063d66675874)

2024-12-31 02:25 UTC, DaleSeo commented on src/styles/globalCss.ts
> +    "--global-font-body": "var(--fonts-sans)",
제가 이전 PR에서 요기에 오타를 내서 현재 웹사이트에 기본 폰트가 적용이 안 되고 있습니다 😆

2024-12-31 02:25 UTC, DaleSeo commented on src/tokens/colors.ts
> +};
시멘틱 색상은 일단 달레 스터디 피그마 파일에서 최대한 가져왔습니다. 앞으로 프로젝트를 진행하면서 지속적으로 개선해나가야 할 부분입니다.

![Shot 2024-12-30 at 21 19 24](https://github.com/user-attachments/assets/3ec62660-ac46-4e4a-9735-5ffa367d1a89)

2024-12-31 02:25 UTC, DaleSeo commented on src/tokens/colors.ts
> +    value: { base: "#160B46", _dark: "#FDFDFF" },
요렇게 `_dark` 키에 다크 모드 용 색상을 지정해줄 수 있습니다.

2024-12-31 02:25 UTC, DaleSeo commented on src/tokens/colors.ts
> +  },
@nhistory 다크 모드에서 배경색은 얘네를 단순히 뒤집으면 될까요? ㅎㅎ 일단 다크 모드 정의는 제외하였습니다.

2024-12-31 02:25 UTC, DaleSeo commented on src/tokens/colors.ts
> +export const colors: Tokens["colors"] = {
TailwindCSS의 색상 팔레트와 OpenProps의 색상 팔레트 중에 고민했습니다. `priamary`와 `secondary` 색이 모두 두 색상 팔레트에 존재하지 않더라구요. 가장 가까운 색을 찾아야할지 고민이네요.

2024-12-31 15:10 UTC, nhistory commented on src/tokens/colors.ts
> +  },
네네 뒤집으면 될 것 같긴 한데, 다크모드 사이트 디자인 적용해보면서 보완해나가야 할 것 같습니다.

2024-12-31 15:14 UTC, nhistory commented on src/tokens/colors.ts
> +export const colors: Tokens["colors"] = {
아 그렇군요. `primary`와 `secondary`색상은 각각 알고달레와 달레의 코드에서 가져왔었는데요.
디자인 시스템 작업하면서 색상 조합을 전체적으로 리뉴얼해보는 것도 고려해보면 좋을 것 같습니다.

2024-12-31 15:17 UTC, nhistory requested changes
다크모드 백그라운드 컬러지정만 추가되면 좋을 것 같습니다.
라이트모드에서 숫자만 반대로 적용 부탁드립니다.

2025-01-04 19:03 UTC, DaleSeo commented on src/tokens/colors.ts
> +export const colors: Tokens["colors"] = {
방대한 TailwindCSS의 색상 팔레트로 쓰는 것이 일관성이 중요한 우리 디자인 시스템의 방향성과 맞지 않는 것 같아서, 달레의 코드와 알고달레에 현재 적용된 색상을 토대로 12 Scale 색상 팔레트를 만들었습니다. 달레의 코드처럼 라이트 모드에서는 teal 계열의 색상이 다크 모드에서는 violet 계열이 색상이 accent 색으로 사용합니다. 여기에 gray, danger, warning 색상을 추가하였습니다. 이렇게 적은 팔레트로 시작하고 컴포넌트를 구현하면서 필요한 색상을 추가했으면 합니다.

2025-01-04 19:06 UTC, DaleSeo commented on src/tokens/colors.ts
> +  },
색상 코드를 하드 코딩하지 않고 팔레트에서 적절한 색을 조합하여 시멘틱 토큰을 재구성하였습니다.

https://github.com/DaleStudy/dale-ui/blob/ab18285b4ef0dbbbf54ec313c57af79680a53f45/src/tokens/colors.ts#L9-L52

2025-01-04 19:12 UTC, DaleSeo commented on src/tokens/colors.mdx
> +- Scale 12: 글자 (high contrast)
이 가이드만 준수하여 색상을 사용하면 명암비로 인한 웹 접근성 문제는 피할 수 있을 거라고 생각합니다.

2025-01-04 19:16 UTC, DaleSeo commented on src/tokens/colors.ts
> +};
커스텀 팔레트를 기준으로 시멘틱 색상도 재작업 하였습니다! 컴포넌트를 구현하면서 펠레트에 있는 색을 직접 쓸 일이 없도록 최대한 용도, 의미별로 상세히 정의하였습니다.

2025-01-06 16:53 UTC, nhistory approved these changes
수고 많으셨습니다!

2025-01-06 21:29 UTC, merged